apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment2
  labels:
    app: nginx-deployment2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deployment2
  template:
    metadata:
      labels:
        app: nginx-deployment2
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: http-nginx
      initContainers:
      - name: delay
        image: busybox
        command: ['sh', '-c', 'until nslookup nginx-service2.default.svc.cluster.local; do echo waiting for nginx-service2; sleep 2; done;']

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service2
spec:
  selector:
    app: nginx-deployment2
  ports:
  - name: http-nginx
    protocol: TCP
    port: 3080
    targetPort: 80