apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: http-nginx
        - containerPort: 443
          name: https-nginx
      - name: network-multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "1180"
        - name: HTTPS_PORT
          value: "11443"
        ports:
        - containerPort: 1180
          name: http-multitool
        - containerPort: 11443
          name: https-multitool
        resources:
          requests:
            cpu: "1m"
            memory: "20Mi"
          limits:
            cpu: "10m"
            memory: "20Mi"          
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-deployment
  ports:
  - name: http-nginx
    protocol: TCP
    port: 2080
    targetPort: 80
  - name: https-nginx
    protocol: TCP
    port: 2443
    targetPort: 443
  - name: http-multitool
    protocol: TCP
    port: 21180
    targetPort: 1180
  - name: https-multitool
    protocol: TCP
    port: 21443
    targetPort: 11443