apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment22
  namespace: default
  labels:
    app: deployment22
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment22
  template:
    metadata:
      labels:
        app: deployment22
    spec:
      volumes:
        - name: my-storage
          persistentVolumeClaim:
            claimName: local-pvc
      containers:
      - name:  busybox
        image:  busybox:latest
        command: ["/bin/sh", "-c"]
        args: ['while sleep 5; do echo "test" >> /data/file.txt; done']
        volumeMounts:
          - name: my-storage
            mountPath: /data
      - name: network-multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "11443"
        volumeMounts:
          - name: my-storage
            mountPath: /data

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  namespace: default
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /tmp/data/

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 100Mi

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer