apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment22
  labels:
    app: deployment22
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment22
  template:
    metadata:
      labels:
        app: deployment22
    spec:
      containers:
      - name:  busybox
        image:  busybox:latest
        command: ["/bin/sh", "-c"]
        args: ['while sleep 5; do echo "test" >> /data/file.txt; done']
        volumeMounts:
          - name: nfs-volume
            mountPath: /data
      - name: network-multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "11443"
        volumeMounts:
          - name: nfs-volume
            mountPath: /data
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: pvcnfs

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvnfs
spec:
  storageClassName: nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs
    server: localhost

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvcnfs
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: pvnfs
