apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment14
  labels:
    app: deployment14
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployment14
  template:
    metadata:
      labels:
        app: deployment14
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: http-nginx
        - containerPort: 443
          name: https-nginx
      - name: network-multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "11443"
        ports:
        - containerPort: 8080
          name: http-multitool
        - containerPort: 11443
          name: https-multitool
        resources:
          requests:
            cpu: "1m"
            memory: "20Mi"
          limits:
            cpu: "10m"
            memory: "20Mi" 
---
apiVersion: v1
kind: Service
metadata:
  name: service-14
spec:
  selector:
    app: deployment14
  ports:
  - name: http-nginx
    protocol: TCP
    port: 9001
    targetPort: 80
  - name: http-multitool
    protocol: TCP
    port: 9002
    targetPort: 8080