apiVersion: v1
kind: Service
metadata:
  name: service-nodeport
spec:
  selector:
    app: deployment14
  ports:
  - name: http-nginx
    protocol: TCP
    port: 80
    nodePort: 30080
  - name: http-multitool
    protocol: TCP
    port: 8080
    nodePort: 30081
  type: NodePort