apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment21
  labels:
    app: deployment21
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment21
  template:
    metadata:
      labels:
        app: deployment21
    spec:
      containers:
      - name:  busybox
        image:  busybox:latest
        command: ["/bin/sh", "-c"]
        args: ['while sleep 5; do echo "test" >> /input/file.txt; done']
        volumeMounts:
        - name: vol
          mountPath: /input
      - name: network-multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "11443"
        volumeMounts:
        - name: vol
          mountPath: /output
      volumes:
      - name: vol
        emptyDir: {}
