apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
  volumes:
    - name: html-content
      configMap:
        name: html-content

---
apiVersion: v1
kind: Service
metadata:
  name: service-nginx
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: NodePort

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: html-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>Homework 2.3</title>
      </head>
      <body>
        <h1>Simple page for NGINX</h1>
      </body>
    </html>